-- MySQL Workbench Synchronization

-- Generated: 2023-04-19 12:30

-- Model: New Model

-- Version: 1.0

-- Project: Name of the project

-- Author: willian.adao

 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

 

CREATE TABLE IF NOT EXISTS `CLARETIANO`.`MUNICIPIOS` (

  `COD_MUNICIPIO` INT(11) NOT NULL,

  `NOM_MUNICIPIO` VARCHAR(100) NOT NULL,

  `NUM_POPULACAO` INT(11) NULL DEFAULT NULL,

  `NOM_PREFEITO` VARCHAR(100) NULL DEFAULT NULL,

  `SGL_UNIDADE_FEDERATIVA` VARCHAR(2) NOT NULL,

  PRIMARY KEY (`COD_MUNICIPIO`),

  INDEX `fk_MUNICIPIOS_UNIDADE_FEDERATIVA_idx` (`SGL_UNIDADE_FEDERATIVA` ASC),

  CONSTRAINT `fk_MUNICIPIOS_UNIDADE_FEDERATIVA`

    FOREIGN KEY (`SGL_UNIDADE_FEDERATIVA`)

   REFERENCES `claretiano`.`UNIDADE_FEDERATIVA` (`SGL_UNIDADE_FEDERATIVA`)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;

 

CREATE TABLE IF NOT EXISTS `CLARETIANO`.`UNIDADE_FEDERATIVA` (

  `SGL_UNIDADE_FEDERATIVA` VARCHAR(2) NOT NULL,

  `NOM_UNIDADE_FEDERATIVA` VARCHAR(100) NOT NULL,

  PRIMARY KEY (`SGL_UNIDADE_FEDERATIVA`))

ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;

 

 

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;